/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package moviesapp;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.util.Objects;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) {
       // Parent root = FXMLLoader.load(getClass().getResource("/app/lyricsapp/view/lyricsapp.fxml"));
        try {
            Parent root = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("/moviesapp.fxml")));
            Scene scene = new Scene(root);
            primaryStage.setTitle("MoviesApp");
            primaryStage.setScene(scene);
            primaryStage.show();
        }catch(Exception e){
            e.printStackTrace();
        }

    }

    public static void main(String[] args) { launch(args); }


}
